name: Go
on:
  workflow_call:

permissions:
  contents: read

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Check out code into the Go module directory
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0

      - name: Set up Go
        uses: ./.github/actions/setup-go-from-dockerfile
        id: go

      - name: Check gofmt
        run: |
          unformatted=$(gofmt -l $(git ls-files '*.go' ':!:vendor/*' ':!:tls1262/*'))
          if [ -n "$unformatted" ]; then
            echo "These files are not gofmt'd:"
            echo "$unformatted"
            exit 1
          fi

      - name: Run go vet
        run: go vet -mod=vendor ./...

      - name: Run tests
        run: |
          go test -mod=vendor -race ./...
